name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          # See src/test/scala/com/snowplowanalytics/snowplow/postgres/loader/Database.scala
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: snowplow
          POSTGRES_PORT: 5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      iglu:
        image: docker://snowplow-docker-registry.bintray.io/snowplow/iglu-server:0.6.1
        args: --config /iglu/server.conf
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run test Iglu Server
    - name: Prepare test environment
      run: ./github/start_environment.sh
    - name: Run tests
      run: sbt clean coverage test
    - name: Submit coveralls data
      if: ${{ always() }}
      run: sbt coverageReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compare SBT version with git tag
      run: .github/check_tag.sh ${GITHUB_REF##*/}
    - name: Docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and publish Docker image
      run: sbt docker:publish
